-- CreateTable
CREATE TABLE `Expense` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `summary` VARCHAR(255) NOT NULL,
    `category` ENUM('HOUSING', 'TRAVEL', 'FOOD', 'UTILITIES', 'INSURANCE', 'HEALTHCARE', 'FINANCIAL', 'LIFESTYLE') NOT NULL DEFAULT 'HOUSING',
    `sum` INTEGER NOT NULL,
    `currency` VARCHAR(191) NOT NULL,
    `paid` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
